Logistic Regression: Binary class labels getter
rust-ml/linfa pull request #325
Opened 2023-12-22 07:58 UTC by DGPardo

Expose a reference to the mapping from the ground truth data label to the assigned binary label used in the logistic regression model.

This goes in line with the output provided by `MultiFittedLogisticRegression` that has a method to access `classes`

2023-12-22 18:07 UTC, quietlychris requested changes
Since these methods/structs are being made public, can you add doc comments for each? Otherwise this looks good, although you may need to rebase onto master. The CI isn't passing right now bc of what looks like a Windows linking issue, but I'll don't think that should gate this being merged.

2023-12-24 11:04 UTC, DGPardo commented
Thanks for your review @quietlychris 
I think I have addressed your requests, otherwise please let me know

2023-12-24 16:36 UTC, quietlychris approved these changes

2023-12-24 16:36 UTC, merged

2023-12-24 16:37 UTC, quietlychris commented
Looks good, thank you!